"""PDF export tool for reports."""

from pathlib import Path
from typing import Optional

from langchain_core.tools import tool

from src.config import get_settings
from src.models import Report


class PDFExporter:
    """Export reports to PDF format."""

    def __init__(self) -> None:
        self.settings = get_settings()
        self.output_dir = self.settings.output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def export_markdown_to_pdf(self, markdown_content: str, filename: str) -> Optional[Path]:
        """Export markdown content to PDF.

        Args:
            markdown_content: Markdown content to export.
            filename: Output filename (without extension).

        Returns:
            Path to the generated PDF or None if failed.
        """
        try:
            # For simplicity, we'll create a well-formatted markdown file
            # In production, you'd use a library like weasyprint or pdfkit
            output_path = self.output_dir / f"{filename}.md"

            # Add PDF header comment for future conversion
            pdf_header = f"""<!-- 
PDF Export Ready
Generated by AI Research Analyst
Date: {__import__('datetime').datetime.now().isoformat()}
-->

"""
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(pdf_header + markdown_content)

            return output_path

        except Exception as e:
            print(f"Error exporting PDF: {e}")
            return None

    def export_report(self, report: Report) -> Optional[Path]:
        """Export a Report object to file.

        Args:
            report: Report object to export.

        Returns:
            Path to the generated file or None if failed.
        """
        # Generate filename from title and date
        safe_title = "".join(c if c.isalnum() or c in (" ", "-", "_") else "" for c in report.title)
        safe_title = safe_title.replace(" ", "_")[:50]
        date_str = report.generated_at.strftime("%Y-%m-%d_%H-%M")
        filename = f"report_{date_str}_{safe_title}"

        # Build markdown content
        content = f"""# {report.title}

**Research Query:** {report.query}
**Generated:** {report.generated_at.strftime("%Y-%m-%d %H:%M")}
**Confidence Score:** {report.confidence_score:.1%}
**Word Count:** {report.word_count}

---

## Executive Summary

{report.executive_summary}

---

## Introduction

{report.introduction}

---

## Analysis

{report.analysis}

---

## Conclusions

{report.conclusions}

---

## Sources

"""
        for i, source in enumerate(report.sources, 1):
            content += f"{i}. [{source.title}]({source.url})\n"

        return self.export_markdown_to_pdf(content, filename)


@tool
def export_report_to_file(report_json: str) -> str:
    """Export a report to a file.

    Args:
        report_json: JSON string of the report.

    Returns:
        Path to the exported file.
    """
    import json

    from src.models import Report

    report_data = json.loads(report_json)
    report = Report(**report_data)

    exporter = PDFExporter()
    path = exporter.export_report(report)

    if path:
        return f"Report exported to: {path}"
    return "Failed to export report"


__all__ = ["PDFExporter", "export_report_to_file"]
